name: Foxblocks Build

# TODO: Add more triggers here, including a workflow_dispatch trigger
on: [ push ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      # Setup gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        