name: Foxblocks Build

# TODO: Add more triggers here, including a workflow_dispatch trigger
on: [ push ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin #TODO: is temurin the best option for this?
          java-version: 8
      
      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      
      # Cache Gradle stuff
      - name: Cache Gradle stuff
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-   

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Gradle Build
        run: ./gradlew build --scan